# Site settings
title: Grayscale
email: tayler.a.blake@gmail.com
url: https://taylerablake.github.io
description: "Here, I present some of my thoughts, which may more often be a reflection of my right brain than of my left."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/taylerwithanE
  - title: facebook
    url: https://www.facebook.com/tayler.a.blake
  - title: instagram
    url: http://https://instagram.com/ohno_itstayler/
  - title: github
    url: https://github.com/taylerablake

# Build settings
markdown: kramdown
permalink: pretty
